service: btc-watcher
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  versionFunctions: false
  memorySize: 128
  region: us-east-2
  stage: dev

functions:
  hello:
    handler: functions/watch/app.handler
    events:
      - http:
          path: /watch
          method: POST

plugins:
  - serverless-offline
  - serverless-python-requirements

# Required to run the python packages correctly
custom:
  pythonRequirements:
    dockerizePip: non-linux